// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  /**
   * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
   */
  interface GetMessageOptions {
    /**
     * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
     */
    escapeLt?: boolean
  }

  export interface WxtI18n extends I18n.Static {
    /**
     * The extension or app ID; you might use this string to construct URLs for resources inside the extension. Even non-localized extensions can use this message.
     * Note: You can't use this message in a manifest file.
     *
     * "<browser.runtime.id>"
     */
    getMessage(
      messageName: "@@extension_id",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "<browser.i18n.getUiLocale()>"
     */
    getMessage(
      messageName: "@@ui_locale",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The text direction for the current locale, either "ltr" for left-to-right languages such as English or "rtl" for right-to-left languages such as Japanese.
     *
     * "<ltr|rtl>"
     */
    getMessage(
      messageName: "@@bidi_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "rtl"; otherwise, it's "ltr".
     *
     * "<rtl|ltr>"
     */
    getMessage(
      messageName: "@@bidi_reversed_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "left"; otherwise, it's "right".
     *
     * "<left|right>"
     */
    getMessage(
      messageName: "@@bidi_start_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "right"; otherwise, it's "left".
     *
     * "<right|left>"
     */
    getMessage(
      messageName: "@@bidi_end_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Claude Chat Cleaner"
     */
    getMessage(
      messageName: "ext_name",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Select and bulk-delete Claude conversations"
     */
    getMessage(
      messageName: "ext_description",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "to bulk select"
     */
    getMessage(
      messageName: "idle_hint",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Select chats"
     */
    getMessage(
      messageName: "btn_select",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Selection mode"
     */
    getMessage(
      messageName: "mode_title",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "select chat"
     */
    getMessage(
      messageName: "key_chat",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "select all"
     */
    getMessage(
      messageName: "key_all",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "clear"
     */
    getMessage(
      messageName: "key_clear",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "delete"
     */
    getMessage(
      messageName: "key_delete",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "exit"
     */
    getMessage(
      messageName: "key_exit",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Clear"
     */
    getMessage(
      messageName: "btn_clear",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Delete 1 chat"
     */
    getMessage(
      messageName: "btn_del1",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Delete $COUNT$ chats"
     */
    getMessage(
      messageName: "btn_delN",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Exit Select mode"
     */
    getMessage(
      messageName: "btn_exit",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "0 chats selected"
     */
    getMessage(
      messageName: "sel0",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "1 chat selected"
     */
    getMessage(
      messageName: "sel1",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "$COUNT$ chats selected"
     */
    getMessage(
      messageName: "selN",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Press ↩ again to delete 1 chat"
     */
    getMessage(
      messageName: "conf1",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Press ↩ again to delete $COUNT$ chats"
     */
    getMessage(
      messageName: "confN",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Deleted 1 chat"
     */
    getMessage(
      messageName: "done1",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Deleted $COUNT$ chats"
     */
    getMessage(
      messageName: "doneN",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Deleted $DONE$, failed $FAILED$"
     */
    getMessage(
      messageName: "doneFail",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Enter Select mode"
     */
    getMessage(
      messageName: "enter",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Exit Select mode"
     */
    getMessage(
      messageName: "exitMode",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Claude Chat Cleaner"
     */
    getMessage(
      messageName: "branding",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    getMessage(
      messageName: "@@extension_id" | "@@ui_locale" | "@@bidi_dir" | "@@bidi_reversed_dir" | "@@bidi_start_edge" | "@@bidi_end_edge" | "ext_name" | "ext_description" | "idle_hint" | "btn_select" | "mode_title" | "key_chat" | "key_all" | "key_clear" | "key_delete" | "key_exit" | "btn_clear" | "btn_del1" | "btn_delN" | "btn_exit" | "sel0" | "sel1" | "selN" | "conf1" | "confN" | "done1" | "doneN" | "doneFail" | "enter" | "exitMode" | "branding",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
  }
}
